import type { Lead } from "./types";

export const INITIAL_LEADS: Lead[] = [
  {
    id: "1",
    date: "2026-04-03",
    followUpDate: null,
    studentName: "Rahul Sharma",
    parentName: "Amit Sharma",
    counsellor: "Priya",
    course: "NEET",
    country: "India",
    phone: "9876543210",
    pipelineSteps: 3,
    rowTone: "new",
    sheetTab: "ongoing",
  },
  {
    id: "2",
    date: "2026-04-03",
    followUpDate: null,
    studentName: "Sneha Patel",
    parentName: "Rajesh Patel",
    counsellor: "Arjun",
    course: "JEE",
    country: "India",
    phone: "9845123456",
    pipelineSteps: 1,
    rowTone: "interested",
    sheetTab: "ongoing",
  },
  {
    id: "3",
    date: "2026-04-02",
    followUpDate: "2026-04-03",
    studentName: "Aryan Mehta",
    parentName: "Sunita Mehta",
    counsellor: "Priya",
    course: "CUET",
    country: "India",
    phone: "9934521678",
    pipelineSteps: 2,
    rowTone: "followup_later",
    sheetTab: "followup",
  },
  {
    id: "4",
    date: "2026-04-02",
    followUpDate: null,
    studentName: "Kavya Nair",
    parentName: "Suresh Nair",
    counsellor: "Ravi",
    course: "NEET",
    country: "India",
    phone: "9812345670",
    pipelineSteps: 4,
    rowTone: "interested",
    sheetTab: "ongoing",
  },
  {
    id: "5",
    date: "2026-04-01",
    followUpDate: null,
    studentName: "Rohan Gupta",
    parentName: "Deepak Gupta",
    counsellor: "Arjun",
    course: "JEE",
    country: "UAE",
    phone: "9867453210",
    pipelineSteps: 1,
    rowTone: "called_no_response",
    sheetTab: "ongoing",
  },
  {
    id: "6",
    date: "2026-04-01",
    followUpDate: null,
    studentName: "Ananya Singh",
    parentName: "Rekha Singh",
    counsellor: "Priya",
    course: "NEET",
    country: "India",
    phone: "9856341290",
    pipelineSteps: 3,
    rowTone: "new",
    sheetTab: "ongoing",
  },
  {
    id: "7",
    date: "2026-03-31",
    followUpDate: null,
    studentName: "Vikram Joshi",
    parentName: "Mahesh Joshi",
    counsellor: "Ravi",
    course: "JEE",
    country: "Singapore",
    phone: "9823456712",
    pipelineSteps: 4,
    rowTone: "interested",
    sheetTab: "converted",
  },
  {
    id: "8",
    date: "2026-03-31",
    followUpDate: null,
    studentName: "Pooja Reddy",
    parentName: "Latha Reddy",
    counsellor: "Arjun",
    course: "CUET",
    country: "India",
    phone: "9898765432",
    pipelineSteps: 2,
    rowTone: "not_interested",
    sheetTab: "not_interested",
  },
  {
    id: "9",
    date: "2026-03-30",
    followUpDate: null,
    studentName: "Amit Kumar",
    parentName: "Sunil Kumar",
    counsellor: "Priya",
    course: "NEET",
    country: "Nepal",
    phone: "9871234560",
    pipelineSteps: 3,
    rowTone: "interested",
    sheetTab: "ongoing",
  },
  {
    id: "10",
    date: "2026-03-30",
    followUpDate: null,
    studentName: "Riya Sharma",
    parentName: "Geeta Sharma",
    counsellor: "Ravi",
    course: "JEE",
    country: "India",
    phone: "9843219870",
    pipelineSteps: 1,
    rowTone: "new",
    sheetTab: "ongoing",
  },
];

export const COURSE_OPTIONS = ["NEET", "JEE", "CUET", "Other"] as const;

export const FACULTY_SEED = [
  {
    id: "f1",
    name: "Dr. Meena Singh",
    subjects: ["Biology", "Chemistry"],
    phone: "9810000001",
    email: "meena@testprepkart.com",
    active: true,
    qualification: "MD",
    experience: 12,
    joined: "2018-04-01",
  },
  {
    id: "f2",
    name: "Mr. Ravi Kumar",
    subjects: ["Physics", "Mathematics"],
    phone: "9810000002",
    email: "ravi@testprepkart.com",
    active: true,
    qualification: "M.Sc",
    experience: 10,
    joined: "2019-06-15",
  },
  {
    id: "f3",
    name: "Ms. Priya Sharma",
    subjects: ["CUET English", "Reasoning"],
    phone: "9810000003",
    email: "priya@testprepkart.com",
    active: true,
    qualification: "MA",
    experience: 8,
    joined: "2020-01-10",
  },
  {
    id: "f4",
    name: "Mr. Arjun Das",
    subjects: ["JEE Mathematics"],
    phone: "9810000004",
    email: "arjun@testprepkart.com",
    active: true,
    qualification: "B.Tech",
    experience: 6,
    joined: "2021-03-01",
  },
];
